//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.8.1
//     from Assets/Scripts/Input Actions Controllers/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;
using UnityEngine;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""user_Input"",
            ""id"": ""54ea8eb1-7501-4d65-b8a1-4bdbf2323683"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""6e357ebc-8673-47a8-af99-1353d7902b82"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""46ac7355-7034-4000-ab19-26daa00df9ad"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""6eef8dac-796b-4189-92bd-dcb273fe09c5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseX"",
                    ""type"": ""Value"",
                    ""id"": ""7cb463a8-850e-4581-968b-c1987c1051c9"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseY"",
                    ""type"": ""Value"",
                    ""id"": ""1bda3e10-4b25-49df-bfde-149d62aca34c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""d3cb2437-a66f-494a-aafa-5d6e90ba3fe6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Scope"",
                    ""type"": ""Button"",
                    ""id"": ""13812270-523e-4263-96dc-dc5d0bf48dfe"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grenade"",
                    ""type"": ""Button"",
                    ""id"": ""9031a243-9b4f-4583-96a2-1fee9f556420"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""1afa071d-3ed5-4c33-9fbb-e95e73e43a32"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Knife"",
                    ""type"": ""Button"",
                    ""id"": ""78eec0e5-a53a-41e3-9927-b83c48453ec1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch_Weapon"",
                    ""type"": ""Value"",
                    ""id"": ""1508d227-1955-40b6-ba29-f115bbf42752"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Peek_Right"",
                    ""type"": ""Button"",
                    ""id"": ""3bf6b28e-ebac-4284-9013-8ee665540983"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Peek_Left"",
                    ""type"": ""Button"",
                    ""id"": ""bd1a773a-7f32-488a-8587-7671444e36fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""4931ceed-5113-41ec-b540-cf8c8a42278b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch_Mode"",
                    ""type"": ""Button"",
                    ""id"": ""0847e0c3-5ea7-4d4c-a58c-035246e932cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5c01ac72-5cae-4881-a154-ed56df78edc3"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80ea27c5-a6f0-4a66-b008-cae6c95dca28"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f9fefdb-0926-487f-b41c-e700545e80a3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db25fc4e-5b32-45b9-adf3-64bf04080d3d"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3922ba71-a0a3-4a46-9d85-cf7fa1b28f43"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Scope"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1312076-2eeb-49b9-9781-eb6654c8dc21"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Scope"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f9d0585-b986-434e-8a27-b8d4464fb9fd"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Grenade"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""522b0878-4fb0-49bc-9d42-9c64eb04271f"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Grenade"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c59020d-6b51-4ba2-a279-4aaaa10cf978"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""051ff134-f928-4d29-a7cb-5bb19bb8e5e2"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76534951-b58f-4cdb-a609-6413e6706299"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Knife"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""106de1da-aec8-4acc-9600-22773d290e76"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Knife"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7fc0bc24-a93c-4e32-9719-5eec2366709b"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Switch_Weapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""021a220f-d0a8-4942-b26e-b8eb7bcbf91c"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": ""Invert"",
                    ""groups"": ""Computer"",
                    ""action"": ""Switch_Weapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2cf12af-c17d-4b7a-9edb-906f6cdf927d"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Switch_Weapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8026b9df-7e49-41df-b7d7-c8fff825cebe"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Computer"",
                    ""action"": ""Switch_Weapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ea8f13a-8caf-49a0-9f66-0ccc18bb00ab"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Peek_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0bc7e49-feab-49fb-8680-579a88f372cc"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Peek_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee0fc8ea-8e9c-48b6-b673-9f8286bfe644"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Peek_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8fe7953-480c-4ccf-b824-78824e096d2e"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Peek_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""6bbc8239-0dbe-4698-a315-2015fd1eb6af"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""21fbd3e0-a944-41a6-a061-c69b177cdef8"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a5f86a8a-1e53-4be4-95da-ed399e80c810"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7312eda2-81ae-4ae9-baf1-798230f0f93b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5537af52-d181-400f-962e-3d6e80313c43"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""e0bc2200-3f9a-4509-9ec5-3102e414bf92"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""7f3a87ef-fb9b-4f85-b401-dfc9d9f785b9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5508e259-25a5-430b-a435-3c43ea8c5c44"",
                    ""path"": ""<XInputController>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ddf2bbf-d348-40bf-9f85-ca712493b1e8"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27883093-68da-4edc-8c5a-0a039d81e184"",
                    ""path"": ""<XInputController>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b795d92b-6298-4619-880a-37768722f433"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": ""Normalize(max=5)"",
                    ""groups"": ""Computer"",
                    ""action"": ""MouseX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f21151f3-1a0c-49c3-afd9-1da7f320d4b0"",
                    ""path"": ""<XInputController>/rightStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""MouseX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c59feeb-aaa9-491e-898c-c776dfaceaf9"",
                    ""path"": ""<Mouse>/delta/y"",
                    ""interactions"": """",
                    ""processors"": ""Normalize(max=5)"",
                    ""groups"": ""Computer"",
                    ""action"": ""MouseY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65bff898-307b-4796-ad83-532e08b251de"",
                    ""path"": ""<XInputController>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""MouseY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34b1cf91-5fb2-4ec3-ad13-76bc3d633903"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Computer"",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40e24da9-08cc-456e-874e-4ebce39b6f9a"",
                    ""path"": ""<XInputController>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca0f81dd-0005-46ae-9f1a-60a5a7567e18"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Computer"",
                    ""action"": ""Switch_Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8986d92-e67d-48a1-97d0-b972c7fabc5b"",
                    ""path"": ""<XInputController>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Switch_Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""user_Input_2"",
            ""id"": ""593bb67c-67e2-48c4-9e68-d01889ecddd2"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""1ad12f02-005e-4d9d-b7d8-acf44c026abc"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""d7126556-32fd-4daa-aba3-fb11351e993d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""3da3dfba-f481-4027-8201-e3a18305c5bd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseX"",
                    ""type"": ""Value"",
                    ""id"": ""5194837b-ad93-4aac-9ddd-d9ee2f4dc250"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseY"",
                    ""type"": ""Value"",
                    ""id"": ""f11a5154-351c-4dac-b2e9-12c544f6a141"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""ec09662d-76ec-47d2-a289-d67d41f50c05"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Scope"",
                    ""type"": ""Button"",
                    ""id"": ""97fa6b00-2086-4133-a50b-2ac71cdfbf44"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grenade"",
                    ""type"": ""Button"",
                    ""id"": ""fa88fc01-2ec0-49be-9eae-5a8dde02214a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""d6ece9e7-0383-4487-b1dd-4773fdf37b23"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Knife"",
                    ""type"": ""Button"",
                    ""id"": ""f5abb8cc-232d-400f-91dc-26c77503092d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch_Weapon"",
                    ""type"": ""Value"",
                    ""id"": ""3bd76de8-ed11-44a4-8189-7b727f7dc58d"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Peek_Right"",
                    ""type"": ""Button"",
                    ""id"": ""c31db19d-4806-45be-8b3b-d636c1d40623"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Peek_Left"",
                    ""type"": ""Button"",
                    ""id"": ""1fe8587a-7c15-4507-91c8-906a457da884"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""1020ad18-7343-44b0-90da-b70597a649c4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch_Mode"",
                    ""type"": ""Button"",
                    ""id"": ""6244ffeb-c64f-4b95-9a9b-c6880992cb00"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""64df4d5b-171d-4d74-b6a3-9df70c1fd96c"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22f78a87-cd05-4866-b54e-cf380157b753"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb251e82-af93-4198-b727-e11a885095eb"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Scope"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28ecd482-d804-4e26-904a-a3faa87511d4"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Grenade"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f0ae22f-202a-4a6c-a1cd-2e273a2166de"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e64b3a5-f8ef-4e75-89c9-a720fe0c29d9"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Knife"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0eafd94-3296-4658-96f1-7ed1bc3189b5"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Switch_Weapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""418aaf76-7eb4-426d-ac4c-ffa32030f920"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Peek_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""387f7bae-9f58-4d34-bf2c-c3ad3edbfc91"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Peek_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61889ac0-cd20-49b7-949d-c71c4f1b6a3f"",
                    ""path"": ""<XInputController>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""836042b4-48c3-4bfd-9c53-9edfa400ee1c"",
                    ""path"": ""<XInputController>/rightStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""MouseX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bdea79b-971a-456d-8db1-680a0903e45c"",
                    ""path"": ""<XInputController>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""MouseY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82a64e72-c884-4211-91ba-f017eb5a6358"",
                    ""path"": ""<XInputController>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9736e53-d315-40a0-9453-4a3801280e68"",
                    ""path"": ""<XInputController>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Switch_Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""46f0e08c-e835-4b8a-ba40-766999bbffd5"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7c6576c9-f945-47ab-93bd-307841907e5d"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""53af947b-93e2-4999-8652-cc1738148905"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""87406260-0950-4a37-bc0b-a5e4a1b3f890"",
                    ""path"": ""<XInputController>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""62ee1cef-060c-4535-9a5e-49b5a7cb7f44"",
                    ""path"": ""<XInputController>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""67cab2c9-6187-4dbc-a529-397ea6a11712"",
                    ""path"": ""<XInputController>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""e7628355-7a64-42aa-967e-9d398a27a175"",
                    ""path"": ""<XInputController>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""user_Input_1"",
            ""id"": ""5d6e0071-1556-4895-b49d-b531b346db58"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""ae42338d-7ade-42d7-bd35-73facd9ae4da"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""4ccdedd6-8140-4d68-a0e8-115d508a1b8d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""82da62bd-028e-4003-861b-ec9391dc2d18"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseX"",
                    ""type"": ""Value"",
                    ""id"": ""93366775-dc77-4eb5-a659-036b62a1ed0c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseY"",
                    ""type"": ""Value"",
                    ""id"": ""7d671a57-b9e8-4e09-beba-24d13863aa76"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""cb9cbfc3-e9e0-489a-a7ff-42966a94f618"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Scope"",
                    ""type"": ""Button"",
                    ""id"": ""e2b309c1-51c0-4693-8aaf-5e4da862651f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grenade"",
                    ""type"": ""Button"",
                    ""id"": ""f25011b4-fa66-462b-a584-1b14858506e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""73c72116-bbcf-4bd1-9b6a-ad0d151f94fe"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Knife"",
                    ""type"": ""Button"",
                    ""id"": ""3dddc556-1a69-4930-8a4a-08440f739021"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch_Weapon"",
                    ""type"": ""Value"",
                    ""id"": ""bbb3edd6-29f7-427d-abaf-4e5203981192"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Peek_Right"",
                    ""type"": ""Button"",
                    ""id"": ""f6642f92-3c60-4297-927c-14286c2d25b4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Peek_Left"",
                    ""type"": ""Button"",
                    ""id"": ""9aed4486-121e-41f5-a0dc-ad8ed69c9b99"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""82e9870f-c079-443c-aaa1-19dca01dd0b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch_Mode"",
                    ""type"": ""Button"",
                    ""id"": ""0a3b6526-5109-4588-9a17-785343128a4a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c488c007-af1f-49ea-a150-3005d71f1177"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4f5e40e-9bf4-44b2-b5dd-58199fc697a3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bea2c34b-3ff7-4786-98ab-ac8686590927"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Scope"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5237f496-01b6-47cf-bf80-6d8364c9fb8d"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Grenade"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a85bbb3d-a459-4ba1-9b41-9e255f4da693"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99f0efaf-bbd5-400c-93c6-3c50e2a6499f"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Knife"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f90e27c-c81e-4502-b5b8-bac9f289c378"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Switch_Weapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57306288-f9a6-4f68-9314-b81ae9bf2a33"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": ""Invert"",
                    ""groups"": ""Computer"",
                    ""action"": ""Switch_Weapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf15db86-d381-48db-af59-fbe84e2f9c5e"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Computer"",
                    ""action"": ""Switch_Weapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""128d7b0b-0d85-4eec-ba55-88e5890ce783"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Peek_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e4a4e9f-f3fd-4c36-9034-948e81d14ac4"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Peek_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""355d5573-a2cb-4159-87ef-6b7fde13a2ef"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3c69f557-fbb2-4fbf-89c8-04c70cb0a0d5"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7ea40b41-e2ba-4068-9948-23c296599500"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0c261b1b-c1ff-44de-99e0-d91a12215b32"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b68c4f41-089c-471d-9e6b-ad4fa7682472"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""24a656f5-cf0f-44fe-99f4-bdbe5d0aedd1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""71baee1e-f902-42e9-8979-861aee594c4b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e81aff22-c8e8-4f79-891d-8f90d0a51f65"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Computer"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9693855b-59aa-40af-9bd4-ac86b0078b76"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": ""Normalize(max=5)"",
                    ""groups"": ""Computer"",
                    ""action"": ""MouseX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1305feb-5006-46f3-8560-4095f06d58b8"",
                    ""path"": ""<Mouse>/delta/y"",
                    ""interactions"": """",
                    ""processors"": ""Normalize(max=5)"",
                    ""groups"": ""Computer"",
                    ""action"": ""MouseY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e4ed908-4414-412c-a64c-84d37d5abe58"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Computer"",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4336499-c4d5-4790-9d5b-1f5aae8a6fef"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Computer"",
                    ""action"": ""Switch_Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Computer"",
            ""bindingGroup"": ""Computer"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Controller"",
            ""bindingGroup"": ""Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // user_Input
        m_user_Input = asset.FindActionMap("user_Input", throwIfNotFound: true);
        m_user_Input_Move = m_user_Input.FindAction("Move", throwIfNotFound: true);
        m_user_Input_Sprint = m_user_Input.FindAction("Sprint", throwIfNotFound: true);
        m_user_Input_Jump = m_user_Input.FindAction("Jump", throwIfNotFound: true);
        m_user_Input_MouseX = m_user_Input.FindAction("MouseX", throwIfNotFound: true);
        m_user_Input_MouseY = m_user_Input.FindAction("MouseY", throwIfNotFound: true);
        m_user_Input_Attack = m_user_Input.FindAction("Attack", throwIfNotFound: true);
        m_user_Input_Scope = m_user_Input.FindAction("Scope", throwIfNotFound: true);
        m_user_Input_Grenade = m_user_Input.FindAction("Grenade", throwIfNotFound: true);
        m_user_Input_Reload = m_user_Input.FindAction("Reload", throwIfNotFound: true);
        m_user_Input_Knife = m_user_Input.FindAction("Knife", throwIfNotFound: true);
        m_user_Input_Switch_Weapon = m_user_Input.FindAction("Switch_Weapon", throwIfNotFound: true);
        m_user_Input_Peek_Right = m_user_Input.FindAction("Peek_Right", throwIfNotFound: true);
        m_user_Input_Peek_Left = m_user_Input.FindAction("Peek_Left", throwIfNotFound: true);
        m_user_Input_Start = m_user_Input.FindAction("Start", throwIfNotFound: true);
        m_user_Input_Switch_Mode = m_user_Input.FindAction("Switch_Mode", throwIfNotFound: true);
        // user_Input_2
        m_user_Input_2 = asset.FindActionMap("user_Input_2", throwIfNotFound: true);
        m_user_Input_2_Move = m_user_Input_2.FindAction("Move", throwIfNotFound: true);
        m_user_Input_2_Sprint = m_user_Input_2.FindAction("Sprint", throwIfNotFound: true);
        m_user_Input_2_Jump = m_user_Input_2.FindAction("Jump", throwIfNotFound: true);
        m_user_Input_2_MouseX = m_user_Input_2.FindAction("MouseX", throwIfNotFound: true);
        m_user_Input_2_MouseY = m_user_Input_2.FindAction("MouseY", throwIfNotFound: true);
        m_user_Input_2_Attack = m_user_Input_2.FindAction("Attack", throwIfNotFound: true);
        m_user_Input_2_Scope = m_user_Input_2.FindAction("Scope", throwIfNotFound: true);
        m_user_Input_2_Grenade = m_user_Input_2.FindAction("Grenade", throwIfNotFound: true);
        m_user_Input_2_Reload = m_user_Input_2.FindAction("Reload", throwIfNotFound: true);
        m_user_Input_2_Knife = m_user_Input_2.FindAction("Knife", throwIfNotFound: true);
        m_user_Input_2_Switch_Weapon = m_user_Input_2.FindAction("Switch_Weapon", throwIfNotFound: true);
        m_user_Input_2_Peek_Right = m_user_Input_2.FindAction("Peek_Right", throwIfNotFound: true);
        m_user_Input_2_Peek_Left = m_user_Input_2.FindAction("Peek_Left", throwIfNotFound: true);
        m_user_Input_2_Start = m_user_Input_2.FindAction("Start", throwIfNotFound: true);
        m_user_Input_2_Switch_Mode = m_user_Input_2.FindAction("Switch_Mode", throwIfNotFound: true);
        // user_Input_1
        m_user_Input_1 = asset.FindActionMap("user_Input_1", throwIfNotFound: true);
        m_user_Input_1_Move = m_user_Input_1.FindAction("Move", throwIfNotFound: true);
        m_user_Input_1_Sprint = m_user_Input_1.FindAction("Sprint", throwIfNotFound: true);
        m_user_Input_1_Jump = m_user_Input_1.FindAction("Jump", throwIfNotFound: true);
        m_user_Input_1_MouseX = m_user_Input_1.FindAction("MouseX", throwIfNotFound: true);
        m_user_Input_1_MouseY = m_user_Input_1.FindAction("MouseY", throwIfNotFound: true);
        m_user_Input_1_Attack = m_user_Input_1.FindAction("Attack", throwIfNotFound: true);
        m_user_Input_1_Scope = m_user_Input_1.FindAction("Scope", throwIfNotFound: true);
        m_user_Input_1_Grenade = m_user_Input_1.FindAction("Grenade", throwIfNotFound: true);
        m_user_Input_1_Reload = m_user_Input_1.FindAction("Reload", throwIfNotFound: true);
        m_user_Input_1_Knife = m_user_Input_1.FindAction("Knife", throwIfNotFound: true);
        m_user_Input_1_Switch_Weapon = m_user_Input_1.FindAction("Switch_Weapon", throwIfNotFound: true);
        m_user_Input_1_Peek_Right = m_user_Input_1.FindAction("Peek_Right", throwIfNotFound: true);
        m_user_Input_1_Peek_Left = m_user_Input_1.FindAction("Peek_Left", throwIfNotFound: true);
        m_user_Input_1_Start = m_user_Input_1.FindAction("Start", throwIfNotFound: true);
        m_user_Input_1_Switch_Mode = m_user_Input_1.FindAction("Switch_Mode", throwIfNotFound: true);
    }

    ~@PlayerInputActions()
    {
        Debug.Assert(!m_user_Input.enabled, "This will cause a leak and performance issues, PlayerInputActions.user_Input.Disable() has not been called.");
        Debug.Assert(!m_user_Input_2.enabled, "This will cause a leak and performance issues, PlayerInputActions.user_Input_2.Disable() has not been called.");
        Debug.Assert(!m_user_Input_1.enabled, "This will cause a leak and performance issues, PlayerInputActions.user_Input_1.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // user_Input
    private readonly InputActionMap m_user_Input;
    private List<IUser_InputActions> m_User_InputActionsCallbackInterfaces = new List<IUser_InputActions>();
    private readonly InputAction m_user_Input_Move;
    private readonly InputAction m_user_Input_Sprint;
    private readonly InputAction m_user_Input_Jump;
    private readonly InputAction m_user_Input_MouseX;
    private readonly InputAction m_user_Input_MouseY;
    private readonly InputAction m_user_Input_Attack;
    private readonly InputAction m_user_Input_Scope;
    private readonly InputAction m_user_Input_Grenade;
    private readonly InputAction m_user_Input_Reload;
    private readonly InputAction m_user_Input_Knife;
    private readonly InputAction m_user_Input_Switch_Weapon;
    private readonly InputAction m_user_Input_Peek_Right;
    private readonly InputAction m_user_Input_Peek_Left;
    private readonly InputAction m_user_Input_Start;
    private readonly InputAction m_user_Input_Switch_Mode;
    public struct User_InputActions
    {
        private @PlayerInputActions m_Wrapper;
        public User_InputActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_user_Input_Move;
        public InputAction @Sprint => m_Wrapper.m_user_Input_Sprint;
        public InputAction @Jump => m_Wrapper.m_user_Input_Jump;
        public InputAction @MouseX => m_Wrapper.m_user_Input_MouseX;
        public InputAction @MouseY => m_Wrapper.m_user_Input_MouseY;
        public InputAction @Attack => m_Wrapper.m_user_Input_Attack;
        public InputAction @Scope => m_Wrapper.m_user_Input_Scope;
        public InputAction @Grenade => m_Wrapper.m_user_Input_Grenade;
        public InputAction @Reload => m_Wrapper.m_user_Input_Reload;
        public InputAction @Knife => m_Wrapper.m_user_Input_Knife;
        public InputAction @Switch_Weapon => m_Wrapper.m_user_Input_Switch_Weapon;
        public InputAction @Peek_Right => m_Wrapper.m_user_Input_Peek_Right;
        public InputAction @Peek_Left => m_Wrapper.m_user_Input_Peek_Left;
        public InputAction @Start => m_Wrapper.m_user_Input_Start;
        public InputAction @Switch_Mode => m_Wrapper.m_user_Input_Switch_Mode;
        public InputActionMap Get() { return m_Wrapper.m_user_Input; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(User_InputActions set) { return set.Get(); }
        public void AddCallbacks(IUser_InputActions instance)
        {
            if (instance == null || m_Wrapper.m_User_InputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_User_InputActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @MouseX.started += instance.OnMouseX;
            @MouseX.performed += instance.OnMouseX;
            @MouseX.canceled += instance.OnMouseX;
            @MouseY.started += instance.OnMouseY;
            @MouseY.performed += instance.OnMouseY;
            @MouseY.canceled += instance.OnMouseY;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @Scope.started += instance.OnScope;
            @Scope.performed += instance.OnScope;
            @Scope.canceled += instance.OnScope;
            @Grenade.started += instance.OnGrenade;
            @Grenade.performed += instance.OnGrenade;
            @Grenade.canceled += instance.OnGrenade;
            @Reload.started += instance.OnReload;
            @Reload.performed += instance.OnReload;
            @Reload.canceled += instance.OnReload;
            @Knife.started += instance.OnKnife;
            @Knife.performed += instance.OnKnife;
            @Knife.canceled += instance.OnKnife;
            @Switch_Weapon.started += instance.OnSwitch_Weapon;
            @Switch_Weapon.performed += instance.OnSwitch_Weapon;
            @Switch_Weapon.canceled += instance.OnSwitch_Weapon;
            @Peek_Right.started += instance.OnPeek_Right;
            @Peek_Right.performed += instance.OnPeek_Right;
            @Peek_Right.canceled += instance.OnPeek_Right;
            @Peek_Left.started += instance.OnPeek_Left;
            @Peek_Left.performed += instance.OnPeek_Left;
            @Peek_Left.canceled += instance.OnPeek_Left;
            @Start.started += instance.OnStart;
            @Start.performed += instance.OnStart;
            @Start.canceled += instance.OnStart;
            @Switch_Mode.started += instance.OnSwitch_Mode;
            @Switch_Mode.performed += instance.OnSwitch_Mode;
            @Switch_Mode.canceled += instance.OnSwitch_Mode;
        }

        private void UnregisterCallbacks(IUser_InputActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @MouseX.started -= instance.OnMouseX;
            @MouseX.performed -= instance.OnMouseX;
            @MouseX.canceled -= instance.OnMouseX;
            @MouseY.started -= instance.OnMouseY;
            @MouseY.performed -= instance.OnMouseY;
            @MouseY.canceled -= instance.OnMouseY;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @Scope.started -= instance.OnScope;
            @Scope.performed -= instance.OnScope;
            @Scope.canceled -= instance.OnScope;
            @Grenade.started -= instance.OnGrenade;
            @Grenade.performed -= instance.OnGrenade;
            @Grenade.canceled -= instance.OnGrenade;
            @Reload.started -= instance.OnReload;
            @Reload.performed -= instance.OnReload;
            @Reload.canceled -= instance.OnReload;
            @Knife.started -= instance.OnKnife;
            @Knife.performed -= instance.OnKnife;
            @Knife.canceled -= instance.OnKnife;
            @Switch_Weapon.started -= instance.OnSwitch_Weapon;
            @Switch_Weapon.performed -= instance.OnSwitch_Weapon;
            @Switch_Weapon.canceled -= instance.OnSwitch_Weapon;
            @Peek_Right.started -= instance.OnPeek_Right;
            @Peek_Right.performed -= instance.OnPeek_Right;
            @Peek_Right.canceled -= instance.OnPeek_Right;
            @Peek_Left.started -= instance.OnPeek_Left;
            @Peek_Left.performed -= instance.OnPeek_Left;
            @Peek_Left.canceled -= instance.OnPeek_Left;
            @Start.started -= instance.OnStart;
            @Start.performed -= instance.OnStart;
            @Start.canceled -= instance.OnStart;
            @Switch_Mode.started -= instance.OnSwitch_Mode;
            @Switch_Mode.performed -= instance.OnSwitch_Mode;
            @Switch_Mode.canceled -= instance.OnSwitch_Mode;
        }

        public void RemoveCallbacks(IUser_InputActions instance)
        {
            if (m_Wrapper.m_User_InputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUser_InputActions instance)
        {
            foreach (var item in m_Wrapper.m_User_InputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_User_InputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public User_InputActions @user_Input => new User_InputActions(this);

    // user_Input_2
    private readonly InputActionMap m_user_Input_2;
    private List<IUser_Input_2Actions> m_User_Input_2ActionsCallbackInterfaces = new List<IUser_Input_2Actions>();
    private readonly InputAction m_user_Input_2_Move;
    private readonly InputAction m_user_Input_2_Sprint;
    private readonly InputAction m_user_Input_2_Jump;
    private readonly InputAction m_user_Input_2_MouseX;
    private readonly InputAction m_user_Input_2_MouseY;
    private readonly InputAction m_user_Input_2_Attack;
    private readonly InputAction m_user_Input_2_Scope;
    private readonly InputAction m_user_Input_2_Grenade;
    private readonly InputAction m_user_Input_2_Reload;
    private readonly InputAction m_user_Input_2_Knife;
    private readonly InputAction m_user_Input_2_Switch_Weapon;
    private readonly InputAction m_user_Input_2_Peek_Right;
    private readonly InputAction m_user_Input_2_Peek_Left;
    private readonly InputAction m_user_Input_2_Start;
    private readonly InputAction m_user_Input_2_Switch_Mode;
    public struct User_Input_2Actions
    {
        private @PlayerInputActions m_Wrapper;
        public User_Input_2Actions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_user_Input_2_Move;
        public InputAction @Sprint => m_Wrapper.m_user_Input_2_Sprint;
        public InputAction @Jump => m_Wrapper.m_user_Input_2_Jump;
        public InputAction @MouseX => m_Wrapper.m_user_Input_2_MouseX;
        public InputAction @MouseY => m_Wrapper.m_user_Input_2_MouseY;
        public InputAction @Attack => m_Wrapper.m_user_Input_2_Attack;
        public InputAction @Scope => m_Wrapper.m_user_Input_2_Scope;
        public InputAction @Grenade => m_Wrapper.m_user_Input_2_Grenade;
        public InputAction @Reload => m_Wrapper.m_user_Input_2_Reload;
        public InputAction @Knife => m_Wrapper.m_user_Input_2_Knife;
        public InputAction @Switch_Weapon => m_Wrapper.m_user_Input_2_Switch_Weapon;
        public InputAction @Peek_Right => m_Wrapper.m_user_Input_2_Peek_Right;
        public InputAction @Peek_Left => m_Wrapper.m_user_Input_2_Peek_Left;
        public InputAction @Start => m_Wrapper.m_user_Input_2_Start;
        public InputAction @Switch_Mode => m_Wrapper.m_user_Input_2_Switch_Mode;
        public InputActionMap Get() { return m_Wrapper.m_user_Input_2; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(User_Input_2Actions set) { return set.Get(); }
        public void AddCallbacks(IUser_Input_2Actions instance)
        {
            if (instance == null || m_Wrapper.m_User_Input_2ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_User_Input_2ActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @MouseX.started += instance.OnMouseX;
            @MouseX.performed += instance.OnMouseX;
            @MouseX.canceled += instance.OnMouseX;
            @MouseY.started += instance.OnMouseY;
            @MouseY.performed += instance.OnMouseY;
            @MouseY.canceled += instance.OnMouseY;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @Scope.started += instance.OnScope;
            @Scope.performed += instance.OnScope;
            @Scope.canceled += instance.OnScope;
            @Grenade.started += instance.OnGrenade;
            @Grenade.performed += instance.OnGrenade;
            @Grenade.canceled += instance.OnGrenade;
            @Reload.started += instance.OnReload;
            @Reload.performed += instance.OnReload;
            @Reload.canceled += instance.OnReload;
            @Knife.started += instance.OnKnife;
            @Knife.performed += instance.OnKnife;
            @Knife.canceled += instance.OnKnife;
            @Switch_Weapon.started += instance.OnSwitch_Weapon;
            @Switch_Weapon.performed += instance.OnSwitch_Weapon;
            @Switch_Weapon.canceled += instance.OnSwitch_Weapon;
            @Peek_Right.started += instance.OnPeek_Right;
            @Peek_Right.performed += instance.OnPeek_Right;
            @Peek_Right.canceled += instance.OnPeek_Right;
            @Peek_Left.started += instance.OnPeek_Left;
            @Peek_Left.performed += instance.OnPeek_Left;
            @Peek_Left.canceled += instance.OnPeek_Left;
            @Start.started += instance.OnStart;
            @Start.performed += instance.OnStart;
            @Start.canceled += instance.OnStart;
            @Switch_Mode.started += instance.OnSwitch_Mode;
            @Switch_Mode.performed += instance.OnSwitch_Mode;
            @Switch_Mode.canceled += instance.OnSwitch_Mode;
        }

        private void UnregisterCallbacks(IUser_Input_2Actions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @MouseX.started -= instance.OnMouseX;
            @MouseX.performed -= instance.OnMouseX;
            @MouseX.canceled -= instance.OnMouseX;
            @MouseY.started -= instance.OnMouseY;
            @MouseY.performed -= instance.OnMouseY;
            @MouseY.canceled -= instance.OnMouseY;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @Scope.started -= instance.OnScope;
            @Scope.performed -= instance.OnScope;
            @Scope.canceled -= instance.OnScope;
            @Grenade.started -= instance.OnGrenade;
            @Grenade.performed -= instance.OnGrenade;
            @Grenade.canceled -= instance.OnGrenade;
            @Reload.started -= instance.OnReload;
            @Reload.performed -= instance.OnReload;
            @Reload.canceled -= instance.OnReload;
            @Knife.started -= instance.OnKnife;
            @Knife.performed -= instance.OnKnife;
            @Knife.canceled -= instance.OnKnife;
            @Switch_Weapon.started -= instance.OnSwitch_Weapon;
            @Switch_Weapon.performed -= instance.OnSwitch_Weapon;
            @Switch_Weapon.canceled -= instance.OnSwitch_Weapon;
            @Peek_Right.started -= instance.OnPeek_Right;
            @Peek_Right.performed -= instance.OnPeek_Right;
            @Peek_Right.canceled -= instance.OnPeek_Right;
            @Peek_Left.started -= instance.OnPeek_Left;
            @Peek_Left.performed -= instance.OnPeek_Left;
            @Peek_Left.canceled -= instance.OnPeek_Left;
            @Start.started -= instance.OnStart;
            @Start.performed -= instance.OnStart;
            @Start.canceled -= instance.OnStart;
            @Switch_Mode.started -= instance.OnSwitch_Mode;
            @Switch_Mode.performed -= instance.OnSwitch_Mode;
            @Switch_Mode.canceled -= instance.OnSwitch_Mode;
        }

        public void RemoveCallbacks(IUser_Input_2Actions instance)
        {
            if (m_Wrapper.m_User_Input_2ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUser_Input_2Actions instance)
        {
            foreach (var item in m_Wrapper.m_User_Input_2ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_User_Input_2ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public User_Input_2Actions @user_Input_2 => new User_Input_2Actions(this);

    // user_Input_1
    private readonly InputActionMap m_user_Input_1;
    private List<IUser_Input_1Actions> m_User_Input_1ActionsCallbackInterfaces = new List<IUser_Input_1Actions>();
    private readonly InputAction m_user_Input_1_Move;
    private readonly InputAction m_user_Input_1_Sprint;
    private readonly InputAction m_user_Input_1_Jump;
    private readonly InputAction m_user_Input_1_MouseX;
    private readonly InputAction m_user_Input_1_MouseY;
    private readonly InputAction m_user_Input_1_Attack;
    private readonly InputAction m_user_Input_1_Scope;
    private readonly InputAction m_user_Input_1_Grenade;
    private readonly InputAction m_user_Input_1_Reload;
    private readonly InputAction m_user_Input_1_Knife;
    private readonly InputAction m_user_Input_1_Switch_Weapon;
    private readonly InputAction m_user_Input_1_Peek_Right;
    private readonly InputAction m_user_Input_1_Peek_Left;
    private readonly InputAction m_user_Input_1_Start;
    private readonly InputAction m_user_Input_1_Switch_Mode;
    public struct User_Input_1Actions
    {
        private @PlayerInputActions m_Wrapper;
        public User_Input_1Actions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_user_Input_1_Move;
        public InputAction @Sprint => m_Wrapper.m_user_Input_1_Sprint;
        public InputAction @Jump => m_Wrapper.m_user_Input_1_Jump;
        public InputAction @MouseX => m_Wrapper.m_user_Input_1_MouseX;
        public InputAction @MouseY => m_Wrapper.m_user_Input_1_MouseY;
        public InputAction @Attack => m_Wrapper.m_user_Input_1_Attack;
        public InputAction @Scope => m_Wrapper.m_user_Input_1_Scope;
        public InputAction @Grenade => m_Wrapper.m_user_Input_1_Grenade;
        public InputAction @Reload => m_Wrapper.m_user_Input_1_Reload;
        public InputAction @Knife => m_Wrapper.m_user_Input_1_Knife;
        public InputAction @Switch_Weapon => m_Wrapper.m_user_Input_1_Switch_Weapon;
        public InputAction @Peek_Right => m_Wrapper.m_user_Input_1_Peek_Right;
        public InputAction @Peek_Left => m_Wrapper.m_user_Input_1_Peek_Left;
        public InputAction @Start => m_Wrapper.m_user_Input_1_Start;
        public InputAction @Switch_Mode => m_Wrapper.m_user_Input_1_Switch_Mode;
        public InputActionMap Get() { return m_Wrapper.m_user_Input_1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(User_Input_1Actions set) { return set.Get(); }
        public void AddCallbacks(IUser_Input_1Actions instance)
        {
            if (instance == null || m_Wrapper.m_User_Input_1ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_User_Input_1ActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @MouseX.started += instance.OnMouseX;
            @MouseX.performed += instance.OnMouseX;
            @MouseX.canceled += instance.OnMouseX;
            @MouseY.started += instance.OnMouseY;
            @MouseY.performed += instance.OnMouseY;
            @MouseY.canceled += instance.OnMouseY;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @Scope.started += instance.OnScope;
            @Scope.performed += instance.OnScope;
            @Scope.canceled += instance.OnScope;
            @Grenade.started += instance.OnGrenade;
            @Grenade.performed += instance.OnGrenade;
            @Grenade.canceled += instance.OnGrenade;
            @Reload.started += instance.OnReload;
            @Reload.performed += instance.OnReload;
            @Reload.canceled += instance.OnReload;
            @Knife.started += instance.OnKnife;
            @Knife.performed += instance.OnKnife;
            @Knife.canceled += instance.OnKnife;
            @Switch_Weapon.started += instance.OnSwitch_Weapon;
            @Switch_Weapon.performed += instance.OnSwitch_Weapon;
            @Switch_Weapon.canceled += instance.OnSwitch_Weapon;
            @Peek_Right.started += instance.OnPeek_Right;
            @Peek_Right.performed += instance.OnPeek_Right;
            @Peek_Right.canceled += instance.OnPeek_Right;
            @Peek_Left.started += instance.OnPeek_Left;
            @Peek_Left.performed += instance.OnPeek_Left;
            @Peek_Left.canceled += instance.OnPeek_Left;
            @Start.started += instance.OnStart;
            @Start.performed += instance.OnStart;
            @Start.canceled += instance.OnStart;
            @Switch_Mode.started += instance.OnSwitch_Mode;
            @Switch_Mode.performed += instance.OnSwitch_Mode;
            @Switch_Mode.canceled += instance.OnSwitch_Mode;
        }

        private void UnregisterCallbacks(IUser_Input_1Actions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @MouseX.started -= instance.OnMouseX;
            @MouseX.performed -= instance.OnMouseX;
            @MouseX.canceled -= instance.OnMouseX;
            @MouseY.started -= instance.OnMouseY;
            @MouseY.performed -= instance.OnMouseY;
            @MouseY.canceled -= instance.OnMouseY;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @Scope.started -= instance.OnScope;
            @Scope.performed -= instance.OnScope;
            @Scope.canceled -= instance.OnScope;
            @Grenade.started -= instance.OnGrenade;
            @Grenade.performed -= instance.OnGrenade;
            @Grenade.canceled -= instance.OnGrenade;
            @Reload.started -= instance.OnReload;
            @Reload.performed -= instance.OnReload;
            @Reload.canceled -= instance.OnReload;
            @Knife.started -= instance.OnKnife;
            @Knife.performed -= instance.OnKnife;
            @Knife.canceled -= instance.OnKnife;
            @Switch_Weapon.started -= instance.OnSwitch_Weapon;
            @Switch_Weapon.performed -= instance.OnSwitch_Weapon;
            @Switch_Weapon.canceled -= instance.OnSwitch_Weapon;
            @Peek_Right.started -= instance.OnPeek_Right;
            @Peek_Right.performed -= instance.OnPeek_Right;
            @Peek_Right.canceled -= instance.OnPeek_Right;
            @Peek_Left.started -= instance.OnPeek_Left;
            @Peek_Left.performed -= instance.OnPeek_Left;
            @Peek_Left.canceled -= instance.OnPeek_Left;
            @Start.started -= instance.OnStart;
            @Start.performed -= instance.OnStart;
            @Start.canceled -= instance.OnStart;
            @Switch_Mode.started -= instance.OnSwitch_Mode;
            @Switch_Mode.performed -= instance.OnSwitch_Mode;
            @Switch_Mode.canceled -= instance.OnSwitch_Mode;
        }

        public void RemoveCallbacks(IUser_Input_1Actions instance)
        {
            if (m_Wrapper.m_User_Input_1ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUser_Input_1Actions instance)
        {
            foreach (var item in m_Wrapper.m_User_Input_1ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_User_Input_1ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public User_Input_1Actions @user_Input_1 => new User_Input_1Actions(this);
    private int m_ComputerSchemeIndex = -1;
    public InputControlScheme ComputerScheme
    {
        get
        {
            if (m_ComputerSchemeIndex == -1) m_ComputerSchemeIndex = asset.FindControlSchemeIndex("Computer");
            return asset.controlSchemes[m_ComputerSchemeIndex];
        }
    }
    private int m_ControllerSchemeIndex = -1;
    public InputControlScheme ControllerScheme
    {
        get
        {
            if (m_ControllerSchemeIndex == -1) m_ControllerSchemeIndex = asset.FindControlSchemeIndex("Controller");
            return asset.controlSchemes[m_ControllerSchemeIndex];
        }
    }
    public interface IUser_InputActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnMouseX(InputAction.CallbackContext context);
        void OnMouseY(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnScope(InputAction.CallbackContext context);
        void OnGrenade(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnKnife(InputAction.CallbackContext context);
        void OnSwitch_Weapon(InputAction.CallbackContext context);
        void OnPeek_Right(InputAction.CallbackContext context);
        void OnPeek_Left(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
        void OnSwitch_Mode(InputAction.CallbackContext context);
    }
    public interface IUser_Input_2Actions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnMouseX(InputAction.CallbackContext context);
        void OnMouseY(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnScope(InputAction.CallbackContext context);
        void OnGrenade(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnKnife(InputAction.CallbackContext context);
        void OnSwitch_Weapon(InputAction.CallbackContext context);
        void OnPeek_Right(InputAction.CallbackContext context);
        void OnPeek_Left(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
        void OnSwitch_Mode(InputAction.CallbackContext context);
    }
    public interface IUser_Input_1Actions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnMouseX(InputAction.CallbackContext context);
        void OnMouseY(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnScope(InputAction.CallbackContext context);
        void OnGrenade(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnKnife(InputAction.CallbackContext context);
        void OnSwitch_Weapon(InputAction.CallbackContext context);
        void OnPeek_Right(InputAction.CallbackContext context);
        void OnPeek_Left(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
        void OnSwitch_Mode(InputAction.CallbackContext context);
    }
}
